name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Python Dependencies
      run: pip install meson ninja
    - uses: actions/checkout@v4
    - name: Configure
      run: meson setup build
    - name: Build
      run: ninja -C build
